### PR TITLE
Fix stripping warped/crimson stems not counting for the StripLogs action

### LINKED ISSUE #1176: StripLogs action does not work for Warped/Crimson Stem, but works for standard logs like Oak
***Detailed description of the issue:**

---
StripLogs action does not work for nether wood/stem types such as Crimson Stem and Warped Stem

It does work for standard overworld wood such as Oak Wood and Dark Oak Wood.
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  StripLogs:
    stripped_crimson_stem:
      income: 0.15
      points: 0.5
      experience: 3.0
```

---

**Jobs version:** 

4.17.1

**Server Type (Spigot/Paper/etc):** 

Airplane

**Server Version (using `/ver`):** 

Airplane 1.16.5-R0.1-SNAPSHOT

### PR DESCRIPTION
**Pull request by MrMacor**
This fixes #1176 by changing how the check for the `StripLogs` action happens. Instead of only firing the action if the version is 1.13+ and the block's type name ends with `_LOG`, the action will now also fire if the version is 1.16+ and the block's type name ends with `_STEM`.

### CODE REVIEW

File: src/main/java/com/gamingmesh/jobs/listeners/JobsPaymentListener.java [hunk 1]
```diff
@@ -1634,7 +1633,11 @@ public void onPlayerInteract(PlayerInteractEvent event) {
 		- Jobs.getNms().getDurability(Jobs.getNms().getItemInMainHand(p)) != hand.getMaxDurability())
 		return;
 
-	    Bukkit.getScheduler().scheduleSyncDelayedTask(plugin, () -> Jobs.action(jPlayer, new BlockActionInfo(block, ActionType.STRIPLOGS), block), 1);
+		// either it's version 1.13+ and we're trying to strip a normal log like oak,
+		// or it's 1.16+ and we're trying to strip a fungi like warped stem
+		if ((Version.isCurrentEqualOrHigher(Version.v1_13_R1) && block.getType().toString().endsWith("_LOG")) ||
+		    (Version.isCurrentEqualOrHigher(Version.v1_16_R1) && block.getType().toString().endsWith("_STEM")))
```
Comment (montlikadani) [inline src/main/java/com/gamingmesh/jobs/listeners/JobsPaymentListener.java:1639]: Also check for `_hyphae`

Comment (MrMacor) [reply src/main/java/com/gamingmesh/jobs/listeners/JobsPaymentListener.java:1639]: Oops, I forgot that existed. I'll also add in a check for `_WOOD` so both `oak_wood` (all-sided bark) and `oak_log` will be counted.
